#1. kubectl run redis-server --image=lfccncf/redis:4 --restart=Never -n app --dry-run -o yaml > q2.yaml
#2. vi q2.yaml
#3. add ports:
#        - containerPort: 6379
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-02-11T06:24:33Z"
  labels:
    run: redis-server
  name: redis-server
  namespace: app
  resourceVersion: "2426"
  selfLink: /api/v1/namespaces/app/pods/redis-server
  uid: 27435655-a6f8-4adb-bada-2c87e378ebd0
spec:
  containers:
  - image: lfccncf/redis:4
    imagePullPolicy: IfNotPresent
    name: redis-server
    ports:
        - containerPort: 6379
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-9bbrz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-9bbrz
    secret:
      defaultMode: 420
      secretName: default-token-9bbrz
status:
  phase: Pending
  qosClass: BestEffort

