#1. kubectl create secret generic some-secret --from-literal=key3=value1
#2. kubectl run nginx-secret --image=nginx --restart=Never --dry-run -o yaml > q3.yaml
#3. vi q3.yaml 

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-02-11T06:36:18Z"
  labels:
    run: nginx-secret
  name: nginx-secret
  namespace: default
  resourceVersion: "3403"
  selfLink: /api/v1/namespaces/default/pods/nginx-secret
  uid: 903ffe47-1e06-488f-b571-1fdf4c3180c7
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx-secret
    env:
      - name: COOL_VARIABLE
        valueFrom:
          secretKeyRef:
            name: some-secret
            key: key3
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-76c57
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-76c57
    secret:
      defaultMode: 420
      secretName: default-token-76c57
status:
  phase: Pending
  qosClass: BestEffort
