#1. create service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testsa
automountServiceAccountToken: false


#2. export deployment
kubectl get deployment test -o yaml > deployment.yaml

#3. edit deployment.yaml add template.spec.serviceAccountName: testsa
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-02-15T03:49:18Z"
  generation: 1
  labels:
    run: test
  name: test
  namespace: default
  resourceVersion: "2107"
  selfLink: /apis/apps/v1/namespaces/default/deployments/test
  uid: f75fa73c-1400-409a-abea-1a1cf60489ba
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: test
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: test
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: testsa
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-15T03:49:25Z"
    lastUpdateTime: "2020-02-15T03:49:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-02-15T03:49:18Z"
    lastUpdateTime: "2020-02-15T03:49:25Z"
    message: ReplicaSet "test-db5495c67" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
  
  #4. kubectl apply -f deployment.yaml  &&  kubectl replace -f deployment.yaml --force && delete/create
  #5. describe the deployment to verify service account